id = "asciidoc"
name = "AsciiDoc"
version = "0.1.3"
schema_version = 1
authors = ["Dunya Kirkali <dunyakirkali@gmail.com>", "Andrei Zvonimir Crnkovic <andrei@0x7f.dev>"]
description = "Support for AsciiDoc syntax"
repository = "https://github.com/dunyakirkali/zed-asciidoc"

[grammars.asciidoc_inline]
repository = "https://github.com/cathaysia/tree-sitter-asciidoc"
commit = "0ecc13042b7352ddc3f7b8b31432e262711d44e4"
path = "tree-sitter-asciidoc_inline"

[grammars.asciidoc]
repository = "https://github.com/cathaysia/tree-sitter-asciidoc"
commit = "0ecc13042b7352ddc3f7b8b31432e262711d44e4"
path = "tree-sitter-asciidoc"
