id = "asciidoc"
name = "AsciiDoc"
version = "0.2.0"
schema_version = 1
authors = ["Dunya Kirkali <dunyakirkali@gmail.com>", "Andrei Zvonimir Crnkovic <andrei@0x7f.dev>"]
description = "Support for AsciiDoc syntax"
repository = "https://github.com/dunyakirkali/zed-asciidoc"

[grammars.asciidoc]
repository = "https://github.com/louiss0/tree-sitter-asciidoc"
commit = "356628c20560416d30de511a7098a3dfca3f8cc1"
